In [1]:
import pandas as pd

In [2]:
import numpy as np

In [6]:
import matplotlib.pyplot as plt

In [8]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/data.csv")

In [9]:
df.head()

   Unnamed: 0  Cust Id  Age  Gender  Income
0           0        1   59    Male    4594
1           1        2   22    Male    4279
2           2        3   32  Female    8245
3           3        4   61    Male    9378
4           4        5   26    Male    1808

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  16 non-null     int64
 1   Cust Id     16 non-null     int64
 2   Age         16 non-null     int64
 3   Gender      16 non-null     object
 4   Income      16 non-null     int64
dtypes: int64(4), object(1)
memory usage: 768.0+ bytes

In [11]:
df.describe(include="all")

        Unnamed: 0    Cust Id        Age Gender       Income
count    16.000000  16.000000  16.000000     16    16.000000
unique         NaN        NaN        NaN      2          NaN
top            NaN        NaN        NaN   Male          NaN
freq           NaN        NaN        NaN     13          NaN
mean      7.500000   8.500000  37.687500    NaN  6048.250000
std       4.760952   4.760952  12.087011    NaN  2342.879496
min       0.000000   1.000000  22.000000    NaN  1808.000000
25%       3.750000   4.750000  28.250000    NaN  4515.250000
50%       7.500000   8.500000  36.000000    NaN  6007.500000
75%      11.250000  12.250000  42.750000    NaN  7971.000000
max      15.000000  16.000000  61.000000    NaN  9378.000000

In [12]:
summary = df.groupby("Gender")["Income"].describe()

In [13]:
summary

,count,mean,std,min,25%,50%,75%,max
Gender,,,,,,,,
Female,3.0,7121.666667,1149.859702,5947.0,6560.0,7173.0,7709.0,8245.0
Male,13.0,5800.538462,2507.281849,1808.0,4279.0,5770.0,7963.0,9378.0

In [14]:
counts = df["Gender"].value_counts().tolist()

In [15]:
counts

[13, 3]

In [16]:
df.groupby("Gender")["Income"].mean()

Gender
Female    7121.666667
Male      5800.538462
Name: Income, dtype: float64

In [17]:
df.groupby("Gender")["Income"].median()

Gender
Female    7173.0
Male      5770.0
Name: Income, dtype: float64

In [18]:
df.groupby("Gender")["Income"].std()

Gender
Female    1149.859702
Male      2507.281849
Name: Income, dtype: float64

In [19]:
df.groupby("Gender")["Income"].quantile(0.25)

Gender
Female    6560.0
Male      4279.0
Name: Income, dtype: float64

In [20]:
df.groupby("Gender")["Income"].quantile(0.50)

Gender
Female    7173.0
Male      5770.0
Name: Income, dtype: float64

In [21]:
df.groupby("Gender")["Income"].quantile(0.75)

Gender
Female    7709.0
Male      7963.0
Name: Income, dtype: float64

In [22]:
df.groupby("Gender")["Income"].min()

Gender
Female    5947
Male      1808
Name: Income, dtype: int64

In [23]:
df.groupby("Gender")["Income"].max()

Gender
Female    8245
Male      9378
Name: Income, dtype: int64

In [24]:
print(1)

1

In [25]:
from google.colab import files

In [26]:
data_to_upload = files.upload()

In [28]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Iris.csv")

In [29]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [30]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [31]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [32]:
df.describe(include = "all")

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
count,150.000000,150.000000,150.000000,150.000000,150.000000,150
unique,NaN,NaN,NaN,NaN,NaN,3
top,NaN,NaN,NaN,NaN,NaN,Iris-setosa
freq,NaN,NaN,NaN,NaN,NaN,50
mean,75.500000,5.843333,3.054000,3.758667,1.198667,NaN
std,43.445368,0.828066,0.433594,1.764420,0.763161,NaN
min,1.000000,4.300000,2.000000,1.000000,0.100000,NaN
25%,38.250000,5.100000,2.800000,1.600000,0.300000,NaN
50%,75.500000,5.800000,3.000000,4.350000,1.300000,NaN
75%,112.750000,6.400000,3.300000,5.100000,1.800000,NaN
max,150.000000,7.900000,4.400000,6.900000,2.500000,NaN

In [33]:
print('Iris-Setosa')
setosa = (df['Species'] == 'Iris-setosa')
print(df[setosa].describe())

print('Iris-Versicolor')
versicolor = (df['Species'] == 'Iris-versicolor')
print(df[versicolor].describe())

print('Iris-Virginica')
virginica = (df['Species'] == 'Iris-virginica')
print(df[virginica].describe())

Iris-Setosa
             Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  50.00000       50.00000     50.000000      50.000000      50.00000
mean   25.50000        5.00600      3.418000       1.464000       0.24400
std    14.57738        0.35249      0.381024       0.173511       0.10721
min     1.00000        4.30000      2.300000       1.000000       0.10000
25%    13.25000        4.80000      3.125000       1.400000       0.20000
50%    25.50000        5.00000      3.400000       1.500000       0.20000
75%    37.75000        5.20000      3.675000       1.575000       0.30000
max    50.00000        5.80000      4.400000       1.900000       0.60000
Iris-Versicolor
              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000      50.000000     50.000000      50.000000     50.000000
mean    75.50000       5.936000      2.770000       4.260000      1.326000
std     14.57738       0.516171      0.313798       0.469911      0.197753
min     51.00000       4.900000      2.000000       3.000000      1.000000
25%     63.25000       5.600000      2.525000       4.000000      1.200000
50%     75.50000       5.900000      2.800000       4.350000      1.300000
75%     87.75000       6.300000      3.000000       4.600000      1.500000
max    100.00000       7.000000      3.400000       5.100000      1.800000
Iris-Virginica
              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000       50.00000     50.000000      50.000000      50.00000
mean   125.50000        6.58800      2.974000       5.552000       2.02600
std     14.57738        0.63588      0.322497       0.551895       0.27465
min    101.00000        4.90000      2.200000       4.500000       1.40000
25%    113.25000        6.22500      2.800000       5.100000       1.80000
50%    125.50000        6.50000      3.000000       5.550000       2.00000
75%    137.75000        6.90000      3.175000       5.875000       2.30000
max    150.00000        7.90000      3.800000       6.900000       2.50000

In [34]:
print('Iris-Setosa')
setosa = (df['Species'] == 'Iris-setosa')
print(df[setosa].describe())

Iris-Setosa
             Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  50.00000       50.00000     50.000000      50.000000      50.00000
mean   25.50000        5.00600      3.418000       1.464000       0.24400
std    14.57738        0.35249      0.381024       0.173511       0.10721
min     1.00000        4.30000      2.300000       1.000000       0.10000
25%    13.25000        4.80000      3.125000       1.400000       0.20000
50%    25.50000        5.00000      3.400000       1.500000       0.20000
75%    37.75000        5.20000      3.675000       1.575000       0.30000
max    50.00000        5.80000      4.400000       1.900000       0.60000

In [35]:
print('Iris-versicolor')
versicolor = (df['Species'] == 'Iris-versicolor')
print(df[versicolor].describe())

Iris-versicolor
              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000      50.000000     50.000000      50.000000     50.000000
mean    75.50000       5.936000      2.770000       4.260000      1.326000
std     14.57738       0.516171      0.313798       0.469911      0.197753
min     51.00000       4.900000      2.000000       3.000000      1.000000
25%     63.25000       5.600000      2.525000       4.000000      1.200000
50%     75.50000       5.900000      2.800000       4.350000      1.300000
75%     87.75000       6.300000      3.000000       4.600000      1.500000
max    100.00000       7.000000      3.400000       5.100000      1.800000

In [36]:
print('Iris-virginica')
virginica = (df['Species'] == 'Iris-virginica')
print(df[virginica].describe())

Iris-virginica
              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000       50.00000     50.000000      50.000000      50.00000
mean   125.50000        6.58800      2.974000       5.552000       2.02600
std     14.57738        0.63588      0.322497       0.551895       0.27465
min    101.00000        4.90000      2.200000       4.500000       1.40000
25%    113.25000        6.22500      2.800000       5.100000       1.80000
50%    125.50000        6.50000      3.000000       5.550000       2.00000
75%    137.75000        6.90000      3.175000       5.875000       2.30000
max    150.00000        7.90000      3.800000       6.900000       2.50000

In [37]:
irisVer = (df['Species'] == 'Iris-versicolor')
print('Iris-versicolor')
print(df[irisVer].describe())

Iris-versicolor
              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000      50.000000     50.000000      50.000000     50.000000
mean    75.50000       5.936000      2.770000       4.260000      1.326000
std     14.57738       0.516171      0.313798       0.469911      0.197753
min     51.00000       4.900000      2.000000       3.000000      1.000000
25%     63.25000       5.600000      2.525000       4.000000      1.200000
50%     75.50000       5.900000      2.800000       4.350000      1.300000
75%     87.75000       6.300000      3.000000       4.600000      1.500000
max    100.00000       7.000000      3.400000       5.100000      1.800000